<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="RSLPTP862" name="Selenium1.TestNGListenerDemoMainClass" tests="8" failures="0" timestamp="15 Feb 2019 10:29:05 GMT" time="0.148" errors="1">
  <testcase name="test2" time="0.006" classname="Selenium1.TestNGListenerDemoMainClass"/>
  <testcase name="test4" time="0.001" classname="Selenium1.TestNGListenerDemoMainClass">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase name="test5" time="0.003" classname="Selenium1.TestNGListenerDemoMainClass">
    <error type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at Selenium1.TestNGListenerDemoMainClass.test5(TestNGListenerDemoMainClass.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- test5 -->
  <testcase name="test8" time="0.002" classname="Selenium1.TestNGListenerDemoMainClass">
    <skipped/>
  </testcase> <!-- test8 -->
  <testcase name="test3" time="0.001" classname="Selenium1.TestNGListenerDemoMainClass"/>
  <testcase name="test7" time="0.000" classname="Selenium1.TestNGListenerDemoMainClass">
    <skipped/>
  </testcase> <!-- test7 -->
  <testcase name="test1" time="0.135" classname="Selenium1.TestNGListenerDemoMainClass"/>
  <testcase name="test6" classname="Selenium1.TestNGListenerDemoMainClass">
    <skipped/>
  </testcase> <!-- test6 -->
</testsuite> <!-- Selenium1.TestNGListenerDemoMainClass -->
