<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="RSLPTP862" name="Selenium1.TimeOutInTestNG" tests="2" failures="0" timestamp="17 Feb 2019 06:11:42 GMT" time="3.075" errors="1">
  <testcase name="setTimeout2" time="2.011" classname="Selenium1.TimeOutInTestNG">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method Selenium1.TimeOutInTestNG.setTimeout2() didn&#039;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method Selenium1.TimeOutInTestNG.setTimeout2() didn't finish within the time-out 2000
at java.util.concurrent.FutureTask.run(FutureTask.java:268)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- setTimeout2 -->
  <testcase name="setTimeOut1" time="1.064" classname="Selenium1.TimeOutInTestNG"/>
</testsuite> <!-- Selenium1.TimeOutInTestNG -->
